#!/usr/bin/env bash

info() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1"
	else
		echo -e "$(tput setaf 2)$1$(tput sgr0)"
	fi
}

error() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1" 1>&2
	else
		echo -e "$(tput setaf 1)$1$(tput sgr0)" 1>&2
	fi
}

if (( $# > 0 )) 
then
	info "Installing version: $1"
	version=$1
else
	info "Installing latest version of knife-client-manager."
	version="latest" 
fi

if (( $UID == 0 )) 
then
	error "Installing as root is not currently supported."
	exit 1
else
	info "Installing as $USER."

	cmd=$(
		cat - <<-EOH
			kcm_home=~/.kcm
			kcm_bashrc=~/.bashrc
		EOH
	)

	eval "$cmd"
fi

kcm_file_tmp=${kcm_file_tmp:-/tmp/knife-client-manager-$version.tar}
kcm_file_remote=${kcm_file_remote:-"https://github.com/downloads/pkopriv2/knife-client-manager/knife-client-manager-$version.tar"}

info "Downloading knife-client-manager."
if ! wget -q -O $kcm_file_tmp $kcm_file_remote
then
	error "Error downloading remote runner [$kcm_file_remote].  Either cannot download or cannot write to file [$kcm_file_tmp]"
	exit 1
fi

info "Unpacking knife-client-manager."
if ! tar -xf $kcm_file_tmp -C /tmp
then
	error "Error unpackaging tmp file [$kcm_tmp_file]"
	exit 1
fi 

info "Installing to home: $kcm_home" 
if ! mv /tmp/knife-client-manager-$version $kcm_home
then
	error "Error moving /tmp/knife-client-manager-$version to $kcm_home"
	exit 1
fi 

info "Adding env entries to: $kcm_bashrc"
if ! grep -q "kcm_home=$kcm_home" $kcm_bashrc
then
	cat - >> $kcm_bashrc <<-EOF

		# Generated by: knife-client-manager
		export kcm_home=$kcm_home
		source $kcm_home/env.sh
	EOF

	if (( $? )) 
	then 
		error "Error updating bashrc [$kcm_home]"
		exit 1
	fi
fi

info "Successfully installed knife-client-manager!  Please source your environment for changes to take effect."
