#!/usr/bin/env bash

info() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1"
	else
		echo -e "$(tput setaf 2)$1$(tput sgr0)"
	fi
}

error() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1" 1>&2
	else
		echo -e "$(tput setaf 1)$1$(tput sgr0)" 1>&2
	fi
}

if (( $# > 0 )) 
then
	info "Installing version: $1"
	version=$1
else
	info "Installing latest version of knife-client-manager."
	version="latest" 
fi

if (( $UID == 0 )) 
then
	error "Installing as root is not currently supported."
	exit 1
fi

kcm_file_tmp=${kcm_file_tmp:-/tmp/kcm.tar}
kcm_file_remote=${kcm_file_remote:-"https://github.com/downloads/pkopriv2/knife-client-manager/knife-client-manager-$version.tar"}

info "Attempting to download tar file: $kcm_file_remote"
if command -v curl &> /dev/null
then
	if ! curl -L $kcm_file_remote > $kcm_file_tmp
	then
		error "Error downloading: $kcm_file_remote.  Either cannot download or cannot write to file: $kcm_file_tmp"
		exit 1
	fi

elif command -v wget &> /dev/null
then
	if ! wget -q -O $kcm_file_tmp $kcm_file_remote
	then
		error "Error downloading: $kcm_file_remote.  Either cannot download or cannot write to file: $kcm_file_tmp"
		exit 1
	fi

else
	error "This installation requires either curl or wget."
	exit 1
fi


info "Installing knife-client-manager."
if ! tar -xf $kcm_file_tmp -C ~
then
	error "Error unpackaging tmp file [$kcm_tmp_file]"
	exit 1
fi 

env_files=( "~/.bashrc" "~/.zshrc" ) 
for file in "${env_files[@]}"
do
	eval "file=$file" # expand the path correctly

	if [[ ! -f $file ]]
	then
		continue
	fi

	if grep -q "source ~/.kcm/env.sh" $file
	then
		continue
	fi

	info "Adding env entries to: $file"
	cat - >> $file <<-EOF

		# Generated by: knife-client-manager
		source ~/.kcm/env.sh
	EOF

	if (( $? )) 
	then 
		error "Error updating file [$file]"
		exit 1
	fi
done

info "Successfully installed knife-client-manager!  Please source your environment for changes to take effect."
